spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # recommandé avec Flyway/Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8082
